In [21]:
from transformers import BertModel, BertTokenizer

In [22]:
model = BertModel.from_pretrained('bert-base-uncased')
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [40]:
tokenizer(['apple pineapple baby <html>', 'apple pie pineapple'])

{'input_ids': [[101, 6207, 7222, 23804, 3336, 1026, 16129, 1028, 102], [101, 6207, 11345, 7222, 23804, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]]}

In [24]:
model.embeddings

BertEmbeddings(
  (word_embeddings): Embedding(30522, 768, padding_idx=0)
  (position_embeddings): Embedding(512, 768)
  (token_type_embeddings): Embedding(2, 768)
  (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
  (dropout): Dropout(p=0.1, inplace=False)
)

In [25]:
tokenizer('<h1 style=123>apple</h1>')

{'input_ids': [101, 1026, 1044, 2487, 2806, 1027, 13138, 1028, 6207, 1026, 1013, 1044, 2487, 1028, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [26]:
help(tokenizer.decode)

Help on method decode in module transformers.tokenization_utils_base:

decode(token_ids: Union[int, List[int], ForwardRef('np.ndarray'), ForwardRef('torch.Tensor'), ForwardRef('tf.Tensor')], skip_special_tokens: bool = False, clean_up_tokenization_spaces: bool = None, **kwargs) -> str method of transformers.models.bert.tokenization_bert.BertTokenizer instance
    Converts a sequence of ids in a string, using the tokenizer and vocabulary with options to remove special
    tokens and clean up tokenization spaces.
    
    Similar to doing `self.convert_tokens_to_string(self.convert_ids_to_tokens(token_ids))`.
    
    Args:
        token_ids (`Union[int, List[int], np.ndarray, torch.Tensor, tf.Tensor]`):
            List of tokenized input ids. Can be obtained using the `__call__` method.
        skip_special_tokens (`bool`, *optional*, defaults to `False`):
            Whether or not to remove special tokens in the decoding.
        clean_up_tokenization_spaces (`bool`, *optional*):
   

In [27]:
tokenizer.decode([101, 7592, 102], skip_special_tokens=True)

2023-12-10 11:40:23.109267: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-10 11:40:23.109310: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-10 11:40:23.109999: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-10 11:40:23.171104: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-10 11:40:24.152215: W tensorflow/compiler/

'hello'

In [28]:
input_ids=input_ids,
token_type_ids=token_type_ids,


NameError: name 'input_ids' is not defined

In [29]:
from torch import LongTensor


model.embeddings(**{'input_ids': LongTensor([[101, 7592, 102]]), 'token_type_ids': LongTensor([[0, 0, 0]])})

tensor([[[ 0.1686, -0.2858, -0.3261,  ..., -0.0276,  0.0383,  0.1640],
         [ 0.3739, -0.0156, -0.2456,  ..., -0.0317,  0.5514, -0.5241],
         [-0.4815, -0.0189,  0.0092,  ..., -0.2806,  0.3895, -0.2815]]],
       grad_fn=<NativeLayerNormBackward0>)

In [30]:
embedding_output = model.embeddings(**{'input_ids': LongTensor([[101, 7592, 102]]), 'token_type_ids': LongTensor([[0, 0, 0]])})

In [35]:
embedding_output.shape
(batch_size, max_seq_len, vec_size)

NameError: name 'batch_size' is not defined

In [36]:
LongTensor([[1, 1, 1]]).shape

torch.Size([1, 3])

In [ ]:
mo

In [39]:
model.encoder(
    embedding_output,
    attention_mask=LongTensor([[1, 1, 1], [3, 3, 3]])
)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 2

In [42]:
token_char_lens = []
for token in  [101, 1026, 1044, 2487, 2806, 1027, 13138, 1028, 6207, 1026, 1013, 1044, 2487, 1028, 102]:
    string_token = tokenizer.decode([token], skip_special_tokens=True)
    if string_token[:2] =='##':
        string_token = string_token[2:]
    if string_token[-2:] =='##':
        string_token = string_token[:2]
    token_char_lens.append(len(string_token))

In [43]:
token_char_lens

[0, 1, 1, 1, 5, 1, 3, 1, 5, 1, 1, 1, 1, 1, 0]

In [25]:
from torch import nn

In [26]:
embedding_output.shape

torch.Size([1, 3, 768])

In [27]:
apple = nn.Linear(768, 768)

In [28]:
apple(embedding_output)

tensor([[[-0.2001,  0.4336,  0.5887,  ..., -0.3227, -0.1087,  0.2730],
         [ 0.0098,  0.0414, -0.1186,  ...,  0.0267, -0.6299, -0.0955],
         [-0.4080,  0.2878,  0.0338,  ..., -0.3930,  0.0195,  0.1860]]],
       grad_fn=<ViewBackward0>)

In [ ]:
from typing import List
def compute_token_char_length(tokens: List[int]) -> List[int]:
    token_char_lens = []
    for token in  tokens:
        string_token = tokenizer.decode([token], skip_special_tokens=True)
        if string_token[:2] =='##':
            string_token = string_token[2:]
        if string_token[-2:] =='##':
            string_token = string_token[:2]
        token_char_lens.append(len(string_token))
    return token_char_lens

In [44]:
from torch import FloatTensor
import torch
import math

def positional_encoding(positions: FloatTensor, d_model=50):
    div_term = torch.exp(torch.arange(0, d_model, 2) * (-math.log(10000.0) / d_model))
    
    pe = torch.zeros(positions.shape[0], d_model)
    positions = positions.unsqueeze(-1)
    pe[:, 0::2] = torch.sin(positions * div_term)
    pe[:, 1::2] = torch.cos(positions * div_term)
    return pe

In [45]:
positional_encoding()

TypeError: positional_encoding() missing 1 required positional argument: 'positions'

In [ ]:
from torch.nn import Dropout, ReLU

class ModifiedBert(nn.Module):
    def __init__(self):
        self.model = BertModel.from_pretrained('bert-base-uncased')
        self.linear = nn.Linear(768, 768)
        self.dropout = Dropout()
        self.relu = ReLU()
        
    def forward(self, input_ids: LongTensor, attention_mask: LongTensor):
        embedding_output = model.embeddings(input_ids=input_ids)
        augmented_input = self.linear(embedding_output)
        augmented_input = self.relu(augmented_input)
        augmented_input = self.dropout(augmented_input)
        out = model.encoder(augmented_input, attention_mask=attention_mask)
        return out

In [13]:
from torch import nn
attention = nn.MultiheadAttention(768, 12)

In [15]:
import torch
attention(torch.FloatTensor([[i for i in range(768)]*3]))

TypeError: MultiheadAttention.forward() missing 2 required positional arguments: 'key' and 'value'

In [17]:
from torch import LongTensor
a = LongTensor([[1,2,3,4,5], [1,2,3,4,5]])

In [20]:
a[:, :2]

tensor([[1, 2],
        [1, 2]])

In [58]:
from torch.utils.data import TensorDataset, DataLoader
from torch import LongTensor
import torch
d = TensorDataset(LongTensor([i for i in range(89*512*768)]).reshape((89, 512, 768)))
DataLoader(d, sampler=None, batch_size=16)

In [59]:
d[0]

(tensor([[     0,      1,      2,  ...,    765,    766,    767],
         [   768,    769,    770,  ...,   1533,   1534,   1535],
         [  1536,   1537,   1538,  ...,   2301,   2302,   2303],
         ...,
         [390912, 390913, 390914,  ..., 391677, 391678, 391679],
         [391680, 391681, 391682,  ..., 392445, 392446, 392447],
         [392448, 392449, 392450,  ..., 393213, 393214, 393215]]),)

In [61]:
[i for i in d]

[(tensor([[     0,      1,      2,  ...,    765,    766,    767],
          [   768,    769,    770,  ...,   1533,   1534,   1535],
          [  1536,   1537,   1538,  ...,   2301,   2302,   2303],
          ...,
          [390912, 390913, 390914,  ..., 391677, 391678, 391679],
          [391680, 391681, 391682,  ..., 392445, 392446, 392447],
          [392448, 392449, 392450,  ..., 393213, 393214, 393215]]),),
 (tensor([[393216, 393217, 393218,  ..., 393981, 393982, 393983],
          [393984, 393985, 393986,  ..., 394749, 394750, 394751],
          [394752, 394753, 394754,  ..., 395517, 395518, 395519],
          ...,
          [784128, 784129, 784130,  ..., 784893, 784894, 784895],
          [784896, 784897, 784898,  ..., 785661, 785662, 785663],
          [785664, 785665, 785666,  ..., 786429, 786430, 786431]]),),
 (tensor([[ 786432,  786433,  786434,  ...,  787197,  787198,  787199],
          [ 787200,  787201,  787202,  ...,  787965,  787966,  787967],
          [ 787968,  78796

In [63]:
torch.concat((torch.LongTensor([[1,2,3], [1,2,3]]), torch.LongTensor([[1,2,3], [1,2,3]])))

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])